[package]
name = "tapedeck"
version = "0.1.0"
authors = ["Zach Thompson <zach@allotropic.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bytes = "0.6.0"
crossterm = { version = "0.18.2", features = ["event-stream"] }
libc = "0.2.81"
libpulse-binding = "2.23.0"
libpulse-simple-binding = "2.23.0"
structopt = "0.3.20"
tokio-stream = "0.1.4"
tracing = { version = "0.1.22", features = ["log"] }
tracing-subscriber = "0.2.15"
tracing-appender = "0.1.2"
tracing-log = "0.1.1"
mime_guess = "2.0.3"
nom = "6.0.1"
pls = "0.2.2"
reqwest = "0.11.1"
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "sqlite", "offline"] }
tokio = { version = "1", features = ["full"] }
url = "2.2.0"
walkdir = "2.3.1"

[dev-dependencies]
log = "0.4.11"
tempfile = "3.2.0"
