[package]
name = "tapedeck"
version = "0.1.0"
authors = ["Zach Thompson <zach@allotropic.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.20"
crossterm = { version = "0.18.2", features = ["event-stream"] }
async-std = "1.7.0"
futures = "0.3.*"
futures-lite = "1.11.3"
async-process = "1.0.1"
libc = "0.2.81"
bytes = "0.6.0"
smol = "1.2.5"
log = "0.4.11"
#slog = "2.7.0"
#slog-async = "2.5.0"
#slog-term = "2.6.0"
#simplelog = "0.8.0"
#async_concur = { path = "../async_concur" }
tracing = { version = "0.1.22", features = ["log"] }
tracing-subscriber = "0.2.15"
tracing-log = "0.1.1"
#ctrlc = "3.1.7"
pls = "0.2.2"
url = "2.2.0"
isahc = "0.9.14"
nom = "6.0.1"
