[package]
name = "tapedeck"
version = "0.1.0"
authors = ["Zach Thompson <zach@allotropic.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.20"
crossterm = { version = "0.18.2", features = ["event-stream"] }
async-std = "1.7.0"
futures = "0.3.*"
futures-lite = "1.11.3"
async-process = "1.0.1"
libc = "0.2.81"
bytes = "0.6.0"
smol = "1.2.5"
log = "0.4.11"
tracing = { version = "0.1.22", features = ["log"] }
tracing-subscriber = "0.2.15"
tracing-appender = "0.1.2"
tracing-log = "0.1.1"
#ctrlc = "3.1.7"
pls = "0.2.2"
url = "2.2.0"
isahc = "0.9.14"
nom = "6.0.1"

mime_guess = "2.0.3"
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "sqlite", "offline"] }
walkdir = "2.3.1"
tokio = { version = "1", features = ["full"] }
