#!/bin/sh
RUNDIR=".tapedeck"
mkdir -p "$RUNDIR"

export RUST_LOG="DEBUG"
export TAPEDECK_DEV_DIR=`realpath "$RUNDIR"`

# Sqlx needs a database to compile
cargo sqlx db setup

if [ $# -eq 0 ]; then
    echo "Please provide args for 'cargo --bin' (e.g. tdplay, tdsearch)"
    exit 1
fi

cmd=$1
shift
cargo run --bin $cmd -- $@
